

CALL ttOptClearStats(,1); 
CALL ttOptEstimateStats(,1, '100 PERCENT'); 

-- begin index capture
Call ttIndexAdviceCaptureStart(1);
autocommit 0;



-- Cumulative code bug statistics over year intervals
SELECT 

  EXTRACT (YEAR FROM RPTDATE) AS "YEAR",
  
  COUNT (*) AS "FILED BUG COUNT",
  COUNT (FIXED_DATE) AS "FIXED BUG COUNT",
  COUNT (CLOSED_DATE) AS "CLOSED BUG COUNT",
  COUNT (*) - COUNT (FIXED_DATE) AS "OPEN BUG COUNT",

  SUM (COUNT (*)) OVER (ORDER BY EXTRACT (YEAR FROM RPTDATE)
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM. FILED BUG COUNT",
    
  SUM (COUNT (FIXED_DATE)) OVER (ORDER BY EXTRACT (YEAR FROM RPTDATE)
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM. FIXED BUG COUNT",
  
  SUM (COUNT (CLOSED_DATE)) OVER (ORDER BY EXTRACT (YEAR FROM RPTDATE)
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM. CLOSED BUG COUNT",    
  
  SUM (COUNT (*) - COUNT (FIXED_DATE)) OVER (ORDER BY EXTRACT (YEAR FROM RPTDATE)
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM. OPEN BUG COUNT"

FROM BUG.RPTHEAD
WHERE RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)

GROUP BY (EXTRACT (YEAR FROM RPTDATE))
ORDER BY (EXTRACT (YEAR FROM RPTDATE)) DESC
;


-- Code bugs broken down by submitter and bug state 
SELECT 

  CASE WHEN GROUPING (RPTD_BY) > 0 
    THEN '** TOTAL **' ELSE RPTD_BY 
    END AS "REPORTED BY", 
  
  COUNT (*) AS "TOTAL BUG COUNT", 
  COUNT (*) - COUNT (FIXED_DATE) AS "OPEN BUG COUNT",
  COUNT (FIXED_DATE) AS "CLOSED BUG COUNT",
  
  ROUND (AVG (CASE WHEN FIXED_DATE IS NULL 
    THEN SYSDATE 
    ELSE FIXED_DATE 
    END - RPTDATE)) AS "AVG DAYS OPEN",
  
  ROUND (AVG (CS_PRIORITY), 1) AS "AVG FILER SEVERITY",
  ROUND (AVG (PRI_FOR_DEV), 1) AS "AVG DEV PRIORITY"

FROM BUG.RPTHEAD

WHERE RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)

GROUP BY ROLLUP (RPTD_BY)
ORDER BY COUNT (*) DESC;




-- All open code bugs broken down by submitter, bug count, and percent of total
SELECT 

  CASE WHEN RPTD_BY IS NULL 
    THEN '** TOTAL **' 
    ELSE RPTD_BY END AS "REPORTED BY", 
  
  COUNT (*) AS "OPEN BUG COUNT",
  
  TO_CHAR (ROUND (COUNT (RPTD_BY) / (SUM (CAST (COUNT (RPTD_BY) AS NUMBER)) 
    OVER (PARTITION BY GROUPING (RPTD_BY))), 2) * 100) || '%' AS PERCENTAGE

FROM BUG.RPTHEAD
WHERE FIXED_DATE IS NULL
  AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
  
GROUP BY ROLLUP (RPTD_BY)
ORDER BY COUNT (RPTD_BY) / (SUM (CAST (COUNT (RPTD_BY) AS NUMBER)) OVER ()) DESC, 1;



-- All open code bugs broken down by severity, bug count, and percent of total
SELECT 

  CASE WHEN GROUPING_ID (CS_PRIORITY) > 0 
    THEN '** TOTAL **' 
    ELSE TO_CHAR (CS_PRIORITY) END AS "SEVERITY",
  
  COUNT (CS_PRIORITY) AS "OPEN BUG COUNT",
  
  TO_CHAR (ROUND (COUNT (CS_PRIORITY) / (SUM (CAST (COUNT (CS_PRIORITY) AS NUMBER)) 
    OVER (PARTITION BY GROUPING_ID (CS_PRIORITY))), 2) * 100) || '%' AS PERCENTAGE

FROM BUG.RPTHEAD
WHERE FIXED_DATE IS NULL 
  AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
  
GROUP BY ROLLUP (CS_PRIORITY)

ORDER BY COUNT (CS_PRIORITY) / 
  (SUM (CAST (COUNT (CS_PRIORITY) AS NUMBER)) 
    OVER (PARTITION BY GROUPING_ID (CS_PRIORITY))) DESC;


-- All open code bugs broken down by dev. priority, bug count, and percent of total
SELECT

  CASE WHEN GROUPING (PRI_FOR_DEV) > 0 
    THEN '** TOTAL **'
    WHEN PRI_FOR_DEV IS NULL 
    THEN 'UNASSIGNED' 
    ELSE PRI_FOR_DEV END AS "PRIORITY", 

  COUNT (*) AS "OPEN BUG COUNT",
  
  TO_CHAR (ROUND (COUNT (*) / (SUM (CAST (COUNT (*) AS NUMBER)) 
    OVER (PARTITION BY GROUPING (PRI_FOR_DEV))), 2) * 100) || '%' AS PERCENTAGE

FROM BUG.RPTHEAD

WHERE FIXED_DATE IS NULL  
  AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
  
GROUP BY ROLLUP (PRI_FOR_DEV)

ORDER BY COUNT (*) / (SUM (CAST (COUNT (*) AS NUMBER)) 
  OVER (PARTITION BY GROUPING (PRI_FOR_DEV))) DESC;


-- All code bugs broken down by status, bug count, and percent of total count
SELECT 
  CASE WHEN GROUPING (HEAD.STATUS) > 0 
    THEN '** TOTAL **' 
    ELSE TO_CHAR (HEAD.STATUS) END AS "STATUS DESCRIPTION",
    
  BUGSTAT.SDESCRIP AS "DESCRIPTION", 
  
  COUNT (*) AS "BUG COUNT",
  
  TO_CHAR (ROUND (COUNT (*) / (SUM (CAST (COUNT (*) AS NUMBER)) 
    OVER (PARTITION BY GROUPING (HEAD.STATUS))), 2) * 100) || '%' AS PERCENTAGE

FROM BUG.RPTHEAD HEAD, BUG.BUGSTAT

WHERE HEAD.STATUS = BUGSTAT.STATUS
  AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)

GROUP BY BUGSTAT.SDESCRIP, CUBE (HEAD.STATUS)
HAVING GROUPING (HEAD.STATUS) > 0

ORDER BY "BUG COUNT" DESC, 1 NULLS FIRST, 2 NULLS FIRST ;


-- For code bugs broken down by version: the average, minimum, maximum and total number of days open
SELECT
  CASE WHEN UTILITY_VERSION IS NULL 
    THEN '** TOTAL **' 
    ELSE UTILITY_VERSION END AS VERSION,
  
  COUNT (RPTNO) AS "BUG COUNT",
  
  ROUND (AVG (CASE WHEN FIXED_DATE IS NULL THEN SYSDATE ELSE FIXED_DATE END - RPTDATE)) AS "AVG DAYS OPEN",
  ROUND (MAX (CASE WHEN FIXED_DATE IS NULL THEN SYSDATE ELSE FIXED_DATE END - RPTDATE)) AS "MAX DAYS OPEN",
  ROUND (MIN (CASE WHEN FIXED_DATE IS NULL THEN SYSDATE ELSE FIXED_DATE END - RPTDATE)) AS "MIN DAYS OPEN"

FROM BUG.RPTHEAD 
WHERE RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)

GROUP BY ROLLUP (UTILITY_VERSION)
ORDER BY COUNT (RPTNO) DESC NULLS FIRST
;


-- A query that reports general code bug count statistics broken down by submitter
-- and product component
WITH RPTHEAD_STATS AS (
 
  SELECT
  
    CASE WHEN GROUPING (RPTD_BY) > 0 
      THEN '** TOTAL **' ELSE RPTD_BY END AS "USER",
    
    CASE WHEN GROUPING (CATEGORY) > 0 
      THEN '** TOTAL **' ELSE CATEGORY END AS "COMPONENT",
   
    COUNT (RPTNO) AS "BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY COUNT (RPTNO) DESC) AS "BUG COUNT RANK",
    
    COUNT (FIXED_DATE) AS "FIXED BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY 
      ORDER BY COUNT (FIXED_DATE) DESC) AS "FIXED BUG COUNT RANK",
  
    COUNT (RPTNO) - COUNT (FIXED_DATE) AS "OPEN BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY 
      ORDER BY COUNT (RPTNO) - COUNT (FIXED_DATE) DESC) AS "OPEN BUG COUNT RANK",
   
    ROUND (AVG (CASE WHEN FIXED_DATE IS NULL 
                THEN SYSDATE 
                ELSE FIXED_DATE END - RPTDATE)) AS "AVG DAYS OPEN",
    DENSE_RANK () OVER (PARTITION BY CATEGORY 
      ORDER BY AVG (CASE WHEN FIXED_DATE IS NULL 
                    THEN SYSDATE 
                    ELSE FIXED_DATE END - RPTDATE) ASC) AS "AVG DAYS OPEN RANK",
   
    ROUND (AVG (CS_PRIORITY), 1) AS "AVG FILER SEVERITY",
    DENSE_RANK () OVER (PARTITION BY CATEGORY 
      ORDER BY AVG (CS_PRIORITY) ASC) AS "AVG FILER SEVERITY RANK",
   
    ROUND (AVG (PRI_FOR_DEV), 1) AS "AVG DEV PRIORITY",
    DENSE_RANK () OVER (PARTITION BY CATEGORY 
      ORDER BY AVG (PRI_FOR_DEV) ASC) AS "AVG DEV PRIORITY RANK"
    
  FROM RPTHEAD 
  
  -- exclude non product bugs
  WHERE RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS) 
      
  GROUP BY CUBE (RPTD_BY, CATEGORY)
  HAVING COUNT (RPTNO) > 100
)

SELECT * FROM RPTHEAD_STATS
ORDER BY "COMPONENT", "BUG COUNT RANK" ASC, "AVG DAYS OPEN RANK" ASC ;



-- A total count of bugs submitted per report day
SELECT 

  TO_CHAR (RPTCALENDAR.RPTDATE, 'YYYY-MON-DD (DY)') AS "RPTDATE",
  COUNT (RPTNO) AS "BUG COUNT"

FROM BUG.RPTHEAD
RIGHT OUTER JOIN BUG.RPTCALENDAR 
 ON TRUNC (RPTHEAD.RPTDATE) = RPTCALENDAR.RPTDATE

GROUP BY RPTCALENDAR.RPTDATE 
ORDER BY RPTCALENDAR.RPTDATE DESC;


-- A total count of bugs submitted per weekday
SELECT 

  CASE WHEN GROUPING (TO_CHAR (RPTCALENDAR.RPTDATE, 'DY')) > 0 
    THEN '** TOTAL **' 
    ELSE TO_CHAR (RPTCALENDAR.RPTDATE, 'DY') END AS "DAY OF WEEK",

  COUNT (RPTNO) AS "BUG COUNT"

FROM BUG.RPTHEAD
RIGHT OUTER JOIN BUG.RPTCALENDAR 
 ON TRUNC (RPTHEAD.RPTDATE) = RPTCALENDAR.RPTDATE

GROUP BY ROLLUP (TO_CHAR (RPTCALENDAR.RPTDATE, 'DY'))
ORDER BY 2 DESC;



-- A query that returns a sliding window average bug count 
SELECT 

  TO_CHAR (RPTCALENDAR.RPTDATE, 'YYYY-MON-DD (DY)') AS "REPORTED DATE",
  COUNT (RPTNO) AS "NEW BUG COUNT",
  
  ROUND (AVG (COUNT (RPTNO))
    OVER (ORDER BY RPTCALENDAR.RPTDATE ASC 
      ROWS BETWEEN 14 PRECEDING AND CURRENT ROW), 1) AS "AVG PER DAY (LAST 14 DAYS)"

FROM BUG.RPTHEAD
RIGHT OUTER JOIN BUG.RPTCALENDAR 
 ON TRUNC (RPTHEAD.RPTDATE) = RPTCALENDAR.RPTDATE 

GROUP BY RPTCALENDAR.RPTDATE
ORDER BY RPTCALENDAR.RPTDATE DESC;



-- A list of all assertion failure bugs
WITH ASSERTION_MSSGS AS (
  
  SELECT 
    RPTNO, 
    LINENO, 
    COMMENTS AS "COMMENT"
  FROM BUG.RPTBODY 
  WHERE UPPER (COMMENTS) LIKE '%ASSERTION FAILED:%'
),

ASSERTION_BUGS AS (

  SELECT 
    RPTHEAD.RPTNO, 
    UTILITY_VERSION AS "VERSION", 
    SUBJECT, 
    LINENO, 
    "COMMENT"
  FROM BUG.RPTHEAD 
  INNER JOIN (SELECT * FROM ASSERTION_MSSGS) ASSERTION_MSSGS
    ON RPTHEAD.RPTNO = ASSERTION_MSSGS.RPTNO
)

SELECT * FROM (

  SELECT DISTINCT 
    RPTNO, 
    VERSION, 
    SUBJECT,   
    FIRST_VALUE ("COMMENT") 
      OVER (PARTITION BY RPTNO ORDER BY LINENO ASC) AS "FIRST COMMENT"  
  FROM ASSERTION_BUGS) ASSERTION_BUG_SUMMARY 

ORDER BY RPTNO DESC
;


-- a ranking based on assertion failure counts
WITH ASSERTION_MSSGS AS (
  
  SELECT DISTINCT
    RPTNO
  FROM BUG.RPTBODY 
  WHERE -- UPPER (COMMENTS) LIKE '%ASSERTION FAILED:%'
   UPPER (COMMENTS) LIKE '%ASSERT%'
),

ASSERTION_BUGS AS (

  SELECT 
    RPTHEAD.RPTNO, 
    CATEGORY,
    RPTD_BY
  FROM BUG.RPTHEAD 
  INNER JOIN (SELECT RPTNO FROM ASSERTION_MSSGS) ASSERTION_MSSGS
    ON RPTHEAD.RPTNO = ASSERTION_MSSGS.RPTNO
)


SELECT 
  CATEGORY,
  RPTD_BY,
  COUNT (RPTNO) AS ASSERTION_BUG_COUNT  
FROM ASSERTION_BUGS
WHERE RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
GROUP BY ROLLUP (CATEGORY, RPTD_BY) 

ORDER BY ASSERTION_BUG_COUNT DESC, 1 NULLS FIRST, 2 NULLS FIRST
;





-- A list of bugs where at least the initial fix was rejected as not fixed

WITH REJECTED_FIXES AS (
  
  SELECT DISTINCT RPTNO
  FROM BUG.RPTBODY 
  WHERE UPPER (COMMENTS) LIKE UPPER ('%Fixed%NULL%')
)

SELECT RPTNO, PROGRAMMER, SUBJECT
FROM BUG.RPTHEAD
WHERE RPTNO IN (SELECT RPTNO FROM REJECTED_FIXES)
ORDER BY PROGRAMMER DESC
;


WITH REJECTED_FIXES AS (
  
  SELECT DISTINCT RPTNO
  FROM BUG.RPTBODY 
  WHERE UPPER (COMMENTS) LIKE UPPER ('%Fixed%NULL%')
)

SELECT PROGRAMMER, COUNT (*)
FROM BUG.RPTHEAD
WHERE RPTNO IN (SELECT RPTNO FROM REJECTED_FIXES)
GROUP BY PROGRAMMER
ORDER BY COUNT (*) DESC
;



-- Query for R analysis of report trends
SELECT 

  ALL_RPTS.MON,  
  
  -- ALL REPORTS --
  ALL_RPTS.RPT_COUNT,
  ALL_VERSIONS.PRODUCT_VERSION,

  CASE WHEN INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT IS NULL 
    THEN 0 
    ELSE INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT 
  END  + 
  
    CASE WHEN EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT IS NULL 
      THEN 0 
      ELSE EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT 
    END AS DEFECT_COUNT,


  CASE WHEN INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT IS NULL 
    THEN 0 
    ELSE INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT 
  END + 
    
    CASE WHEN EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT IS NULL 
      THEN 0 
      ELSE EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT 
    END AS DEFECT_FIXED_COUNT,
  
    
  -- INTERNAL REPORTS --    
  CASE WHEN INTERNAL_RPT_COUNT IS NULL 
    THEN 0 
    ELSE INTERNAL_RPT_COUNT 
  END AS INTERNAL_RPT_COUNT, 
    
  CASE WHEN INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT IS NULL 
    THEN 0 
    ELSE INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT 
  END AS INTERNAL_DEFECT_COUNT,    
    
  CASE WHEN INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT IS NULL 
    THEN 0 
    ELSE INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT 
  END AS INTERNAL_DEFECT_FIXED_COUNT,
          


  -- EXTERNAL REPORTS --   
  CASE WHEN EXTERNAL_RPT_COUNT IS NULL 
    THEN 0 
    ELSE EXTERNAL_RPT_COUNT 
  END AS EXTERNAL_RPT_COUNT, 

    
  CASE WHEN EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT IS NULL 
    THEN 0 
    ELSE EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT 
  END AS EXTERNAL_DEFECT_COUNT,    
    
  CASE WHEN EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT IS NULL 
    THEN 0 
    ELSE EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT 
  END AS EXTERNAL_DEFECT_FIXED_COUNT
  
  
    
FROM 

  (SELECT 
    
      TRUNC(RPTDATE, 'MON') AS MON,
      COUNT (*) AS RPT_COUNT
      
   FROM BUG.RPTHEAD 
   WHERE CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(RPTDATE, 'MON')) ALL_RPTS,
   
  (SELECT DISTINCT

    TRUNC(RPTDATE, 'MON') AS MON,
    FIRST_VALUE (UTILITY_VERSION) 
      OVER (PARTITION BY TRUNC(RPTDATE, 'MON')
        ORDER BY COUNT (*) DESC, MAX (UTILITY_VERSION) DESC) PRODUCT_VERSION

   FROM BUG.RPTHEAD
   WHERE CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(RPTDATE, 'MON'), UTILITY_VERSION) ALL_VERSIONS,


  
   -- INTERNAL REPORTS --   
  (SELECT 
  
    TRUNC(RPTDATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_RPT_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO NOT IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
    AND CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(RPTDATE, 'MON')) INTERNAL_RPTS,
   
  (SELECT 
  
    TRUNC(RPTDATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_DEFECT_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO NOT IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
     AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
   GROUP BY TRUNC(RPTDATE, 'MON')) INTERNAL_DEFECTS,
   
  (SELECT 
  
    TRUNC(FIXED_DATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_DEFECT_FIXED_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO NOT IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
     AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
     AND FIXED_DATE IS NOT NULL
   GROUP BY TRUNC(FIXED_DATE, 'MON')) INTERNAL_DEFECTS_FIXED,
   
   
   
  -- EXTERNAL REPORTS --   
  (SELECT 
  
    TRUNC(RPTDATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_RPT_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
    AND CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(RPTDATE, 'MON')) EXTERNAL_RPTS,
   
  (SELECT 
  
    TRUNC(RPTDATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_DEFECT_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
     AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
   GROUP BY TRUNC(RPTDATE, 'MON')) EXTERNAL_DEFECTS,
  
  (SELECT 
  
    TRUNC(FIXED_DATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_DEFECT_FIXED_COUNT
    
   FROM BUG.RPTHEAD
   WHERE RPTNO IN (SELECT RPTNO FROM BUG.CUSTOMER_BUGS)
     AND RPTNO IN (SELECT * FROM BUG.V_CODE_BUGS)
     AND FIXED_DATE IS NOT NULL
   GROUP BY TRUNC(FIXED_DATE, 'MON')) EXTERNAL_DEFECTS_FIXED  
  
  
WHERE (
  ALL_RPTS.MON = ALL_VERSIONS.MON(+) AND
  
  ALL_RPTS.MON = INTERNAL_RPTS.MON(+) AND 
  ALL_RPTS.MON = INTERNAL_DEFECTS.MON(+) AND 
  ALL_RPTS.MON = INTERNAL_DEFECTS_FIXED.MON(+) AND
  
  ALL_RPTS.MON = EXTERNAL_RPTS.MON(+) AND 
  ALL_RPTS.MON = EXTERNAL_DEFECTS.MON(+) AND
  ALL_RPTS.MON = EXTERNAL_DEFECTS_FIXED.MON(+))

ORDER BY 1 DESC;


-- general metadata queries


-- This query displays all users who have reported bugs.
SELECT

	CASE WHEN GROUPING (RPTHEAD.RPTD_BY) = 0
	  THEN RPTHEAD.RPTD_BY 
	  ELSE '<All>'
	  END AS "REPORTED_BY",
		
	CASE WHEN GROUPING (RPTHEAD.RPTD_BY) = 0	
	  THEN RPTHEAD.RPTD_BY ELSE '%' 
	  END AS "VALUE"
	
FROM BUG.RPTHEAD
GROUP BY ROLLUP (RPTHEAD.RPTD_BY)

ORDER BY RPTHEAD.RPTD_BY ASC NULLS FIRST;



-- This query displays all users who have assigned bugs.
SELECT

	CASE WHEN GROUPING (RPTHEAD.PROGRAMMER) = 0
	  THEN RPTHEAD.PROGRAMMER 
	  ELSE '<All>' -- 
	  END AS "ASSIGNED_TO",
		
	CASE WHEN GROUPING (RPTHEAD.PROGRAMMER) = 0	
	  THEN RPTHEAD.PROGRAMMER ELSE '%' 
	  END AS "VALUE"
	
FROM BUG.RPTHEAD
GROUP BY ROLLUP (RPTHEAD.PROGRAMMER)

ORDER BY RPTHEAD.PROGRAMMER ASC NULLS FIRST;



-- This query displays all components for reported bugs
-- and the number of bugs associated with a component. 
SELECT

	CASE WHEN GROUPING (RPTHEAD.CATEGORY) = 0 
	  THEN RPTHEAD.CATEGORY || ' (' || 
	    COUNT (RPTHEAD.CATEGORY) || ')'
	  ELSE '<All> (' || COUNT (*) || ')'
      END AS "COMPONENT",
	
    CASE WHEN GROUPING (RPTHEAD.CATEGORY) = 0  
      THEN RPTHEAD.CATEGORY ELSE '%'
      END AS "VALUE"

FROM BUG.RPTHEAD
GROUP BY ROLLUP (RPTHEAD.CATEGORY)

ORDER BY RPTHEAD.CATEGORY ASC NULLS FIRST;


-- This query displays customers associated with reported bugs
-- and the number of bugs associated with each customer.
SELECT CUSTOMER, VALUE  FROM (

  SELECT
    
    CASE       
      WHEN GROUPING (ORG) = 1
      THEN '<External> (' || COUNT (ORG) || ')'
      WHEN GROUPING (ORG) = 0 AND ORG IS NOT NULL
      THEN ORG || ' (' || COUNT (ORG) || ')'
      ELSE '<Internal> (' || COUNT (*) || ')'
      END AS "CUSTOMER",
    
    CASE 
      WHEN GROUPING (ORG) = 1
      THEN '%'
      WHEN GROUPING (ORG) = 0 AND ORG IS NOT NULL
      THEN ORG 
      ELSE '<Internal>'
      END AS "VALUE",
      
    CASE       
      WHEN GROUPING (ORG) = 1
      THEN COUNT (ORG) 
   	  WHEN ORG IS NOT NULL
   	  THEN NULL 
   	  ELSE COUNT (*) END AS "GROUP_COUNT"   
    
  FROM RPTHEAD 
  LEFT OUTER JOIN (
    /* select a maximum of one customer per bug report */
    SELECT DISTINCT 
      RPTNO, 
      
      -- This expression takes 13 secs. in TimesTen.
      -- Avoiding this adds extra rows to the result
      -- and an incorrect RPTNO count for <External>.
      FIRST_VALUE (ORG) 
        OVER (PARTITION BY RPTNO ORDER BY ORG ASC) AS ORG 
        
    FROM CUSTOMER_BUGS
    WHERE ORG IS NOT NULL) CUST_BUGS
    ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO
  
  GROUP BY ROLLUP (ORG)
  
  UNION
  
  SELECT 
  	'<All> (' || COUNT (*) || ')' AS "CUSTOMER",
  	'<All>' AS "VALUE",
  	COUNT (*) AS "GROUP_COUNT"
  FROM RPTHEAD)

ORDER BY GROUP_COUNT DESC NULLS LAST, CUSTOMER;




-- Displays all priorites for reported bugs and the number 
-- of bugs associated with a priority. 
SELECT

	CASE WHEN GROUPING (RPTHEAD.PRI_FOR_DEV) = 0 
	THEN 
	
	  CASE 
	    WHEN RPTHEAD.PRI_FOR_DEV IS NULL
	      THEN '<Unassigned>'
	    WHEN RPTHEAD.PRI_FOR_DEV = 1
	      THEN RPTHEAD.PRI_FOR_DEV || 
	        ' - At Earliest Opportunity'
	    WHEN RPTHEAD.PRI_FOR_DEV = 2
	      THEN RPTHEAD.PRI_FOR_DEV || 
	        ' - By Next Distributed Version'
	    WHEN RPTHEAD.PRI_FOR_DEV = 3
	      THEN RPTHEAD.PRI_FOR_DEV || 
	        ' - By Next Release'
	    WHEN RPTHEAD.PRI_FOR_DEV = 4
	      THEN RPTHEAD.PRI_FOR_DEV || 
	        ' - Scheduled for a Later Release'
	    WHEN RPTHEAD.PRI_FOR_DEV = 5
	      THEN RPTHEAD.PRI_FOR_DEV || 
	        ' - Not Scheduled'	        
	  END
	
	  || ' (' || COUNT (*) || ')'
	  
	ELSE '<All> (' || COUNT (*) || ')'
    END AS "PRIORITY",
	
    CASE WHEN GROUPING (RPTHEAD.PRI_FOR_DEV) = 1
      THEN '%'  
      WHEN RPTHEAD.PRI_FOR_DEV IS NULL
      THEN '<Unassigned>'
      ELSE RPTHEAD.PRI_FOR_DEV
      END AS "VALUE"

FROM BUG.RPTHEAD

GROUP BY ROLLUP (RPTHEAD.PRI_FOR_DEV)

ORDER BY RPTHEAD.PRI_FOR_DEV ASC NULLS FIRST;




-- This query displays all severities for reported bugs
-- and the number of bugs associated with a severity. 
SELECT

	CASE WHEN GROUPING (RPTHEAD.CS_PRIORITY) = 0 
	THEN RPTHEAD.CS_PRIORITY || ' - ' || 
	
	  CASE 
	    WHEN RPTHEAD.CS_PRIORITY = 1
	      THEN 'Complete Loss of Service'
	    WHEN RPTHEAD.CS_PRIORITY = 2
	      THEN 'Severe Loss of Service'
	    WHEN RPTHEAD.CS_PRIORITY = 3
	      THEN 'Minimal Loss of Service'
	    WHEN RPTHEAD.CS_PRIORITY = 4
	      THEN 'Minor Error, No Loss of Service'
	  END
	
	  || ' (' || COUNT (RPTHEAD.CS_PRIORITY) || ')'
	  
	ELSE '<All> (' || COUNT (*) || ')'
    END AS "SEVERITY",
	
    CASE WHEN GROUPING (RPTHEAD.CS_PRIORITY) = 0  
      THEN TO_CHAR (RPTHEAD.CS_PRIORITY) 
      ELSE '%' END AS "VALUE"

FROM BUG.RPTHEAD
GROUP BY ROLLUP (RPTHEAD.CS_PRIORITY)

ORDER BY RPTHEAD.CS_PRIORITY ASC NULLS FIRST;


-- This query displays all states for reported bugs
-- and the number of bugs associated with a state. 
SELECT 
  STATUS AS "_UVIEW1", -- STATUS --
  "VALUE" AS "_UVIEW2" -- VALUE --
FROM (

  SELECT

	BUGSTAT.STATUS || ' - ' || SDESCRIP ||
      ' (' || COUNT (RPTNO) || ')'  AS "STATUS",		
		
	TO_CHAR (BUGSTAT.STATUS) AS "VALUE",
      
    COUNT (RPTNO) AS "DISPLAY_ORDER",
    
	0 AS "STATE_VALUE"

  FROM BUG.BUGSTAT, BUG.RPTHEAD
  WHERE BUGSTAT.STATUS = RPTHEAD.STATUS
  GROUP BY (BUGSTAT.STATUS, SDESCRIP)

  UNION

  SELECT
  
    CASE WHEN GROUPING (BUGSTAT_STATE.STATE) = 0 
      THEN '<' || BUGSTAT_STATE.STATE || '> (' 
      	|| COUNT (RPTNO) || ')'
      ELSE '<All> (' || COUNT (RPTNO) || ')'
      END AS "STATUS",
    
    CASE WHEN GROUPING (BUGSTAT_STATE.STATE) = 0 
      THEN '<' || BUGSTAT_STATE.STATE || '>'  
      ELSE '%'
      END AS "VALUE",
    
    COUNT (RPTNO) AS "DISPLAY_ORDER",
    
    1 AS "STATE_VALUE"
      
  FROM BUG.BUGSTAT, BUG.BUGSTAT_STATE, BUG.RPTHEAD
  WHERE BUGSTAT.STATUS = RPTHEAD.STATUS
    AND BUGSTAT.STATUS = BUG.BUGSTAT_STATE.STATUS
  
  GROUP BY ROLLUP (BUGSTAT_STATE.STATE))

ORDER BY STATE_VALUE DESC, DISPLAY_ORDER DESC;





-- This query displays all versions for reported bugs
-- and the number of bugs associated with each version. 
SELECT * FROM (
  SELECT 

	CASE WHEN GROUPING (RPTHEAD.UTILITY_VERSION) = 0
	THEN RPTHEAD.UTILITY_VERSION || ' (' ||
	  COUNT (RPTHEAD.UTILITY_VERSION) || ')'
	ELSE '<All> (' || COUNT (*) || ')'
	END AS "_UVIEW1", -- VERSION --
	
	CASE WHEN GROUPING (RPTHEAD.UTILITY_VERSION) = 0
	THEN RPTHEAD.UTILITY_VERSION ELSE '%'
	END AS "_UVIEW2" -- VALUE --
	
  FROM BUG.RPTHEAD
  GROUP BY ROLLUP (RPTHEAD.UTILITY_VERSION)

  UNION

  SELECT 
    '<' || SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 3) - 1) || 
      '%> (' || COUNT (*) || ')' AS "_UVIEW1", -- VERSION --
      
    SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 3) - 1) || 
      '%' AS "_UVIEW2" -- VALUE --
  
  FROM BUG.RPTHEAD
  
  GROUP BY (SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 3) - 1))
  HAVING COUNT (*) >= 100 AND 
    SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 3) - 1)  IS NOT NULL

  UNION

  SELECT 
    '<' || SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 2) - 1) || 
      '%> (' || COUNT (*) || ')' AS "_UVIEW1", -- VERSION --
      
    SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 2) - 1) || 
      '%' AS "_UVIEW2" -- VALUE --
  
  FROM BUG.RPTHEAD
  
  GROUP BY (SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 2) - 1))
  HAVING COUNT (*) >= 1000 AND 
    SUBSTR (UTILITY_VERSION, 1, INSTR (UTILITY_VERSION, '.', 1, 2) - 1)  IS NOT NULL)

ORDER BY "_UVIEW1" DESC NULLS FIRST;



-- keyword serach
prepare 1
WITH SEARCH_TERMS AS
(
  SELECT 
    '%' || WILDCARD AS SEARCH_STRING,
    SUBSTR (WILDCARD, 0, 
      INSTR (WILDCARD, '%') - 1) AS COMMENT_SEARCH_STRING
  FROM 
    (SELECT 
      LTRIM (REPLACE (UPPER (:search), ' ', '%'), '%') || '%' AS WILDCARD
    FROM DUAL) UPPER_RIGHT_WILDCARD
)

SELECT DISTINCT 

  RPTHEAD.RPTNO, 
  UTILITY_VERSION AS "VERSION", 
  RPTHEAD.CATEGORY AS "COMPONENT",
  BUGSTAT.STATUS || ' - ' || BUGSTAT.SDESCRIP AS "STATUS",
  BUGSTAT_STATE.STATE,
  SUBJECT,
  
  '... ' || LTRIM (
    FIRST_VALUE (COMMENTS) 
      OVER (PARTITION BY RPTBODY.RPTNO 
        ORDER BY INSTR (COMMENTS, COMMENT_SEARCH_STRING) DESC NULLS LAST),
    ' @.') || ' ...' AS "COMMENT"

FROM BUG.RPTHEAD, BUG.RPTBODY, 
  BUG.BUGSTAT, BUG.BUGSTAT_STATE,
  SEARCH_TERMS

WHERE RPTHEAD.RPTNO = RPTBODY.RPTNO
  AND RPTHEAD.STATUS = BUGSTAT.STATUS
  AND BUGSTAT.STATUS = BUGSTAT_STATE.STATUS
  
AND ((UPPER (COMMENTS) LIKE SEARCH_STRING)
  OR (UPPER (SUBJECT) LIKE SEARCH_STRING))    

    
  /* handle Status cases */    
  AND (RPTHEAD.STATUS LIKE :status1
  	OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')

ORDER BY 1 DESC;


-- RPTNO query
prepare 2
WITH CUST_BUGS AS (
  
  /* select a maximum of one customer per bug report */
  SELECT DISTINCT 
    RPTNO, 
    FIRST_VALUE (ORG) 
      OVER (PARTITION BY RPTNO ORDER BY ORG DESC) AS ORG 
  FROM BUG.CUSTOMER_BUGS
  WHERE RPTNO = :rptno 
  	AND ORG IS NOT NULL
)

SELECT

  RPTHEAD.RPTNO,
  RPTHEAD.SUBJECT AS "SUBJECT",
      
  CASE WHEN SYSDATE - RPTHEAD.RPTDATE < 7
    THEN TO_CHAR (RPTHEAD.RPTDATE, 'DAY')
    ELSE TO_CHAR (RPTHEAD.RPTDATE, 'DS')
    END AS "DATE",
      	
  RPTHEAD.RPTD_BY AS "REPORTED_BY",
  RPTHEAD.PROGRAMMER AS "ASSIGNED_TO",
  RPTHEAD.UTILITY_VERSION AS "VERSION",
  BUGSTAT.STATUS || ' - ' || BUGSTAT.SDESCRIP AS "STATUS",
  BUGSTAT.STATUS AS "STATUS_CODE",
  BUGSTAT_STATE.STATE AS "STATE",
  RPTHEAD.CS_PRIORITY AS "SEVERITY",
      
  CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL
    THEN '<Unassigned>' ELSE RPTHEAD.PRI_FOR_DEV
    END AS "PRIORITY",
        
  RPTHEAD.CATEGORY AS "COMPONENT",
      
  CASE WHEN CUST_BUGS.ORG IS NULL
    THEN '<Internal>' ELSE CUST_BUGS.ORG 
    END AS "CUSTOMER",
      	
  BASE_RPTNO
      
      
FROM BUG.RPTHEAD 
JOIN BUG.BUGSTAT ON RPTHEAD.STATUS = BUGSTAT.STATUS 
JOIN BUG.BUGSTAT_STATE ON RPTHEAD.STATUS = BUGSTAT_STATE.STATUS 
LEFT OUTER JOIN CUST_BUGS ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO

WHERE RPTHEAD.RPTNO = :rptno

ORDER BY RPTHEAD.RPTNO DESC;


-- RPTBODY query
prepare 3
SELECT

  CASE WHEN LINE_TYPE = 'A'
   THEN '<B>' || REPLACE (LTRIM (RPTBODY.COMMENTS, ' @.'), '***') || '</B><BR>'
   ELSE LTRIM (RPTBODY.COMMENTS, ' @.') || '<BR>'
   END AS LINE,
   
   LINE_TYPE

FROM BUG.RPTBODY
WHERE RPTBODY.RPTNO = :rptno
ORDER BY LINENO;



-- RPTBODY query
prepare 4
WITH CUST_BUGS AS (
  
  /* select a maximum of one customer per bug report */
  SELECT DISTINCT 
    RPTNO, 
    FIRST_VALUE (ORG) 
      OVER (PARTITION BY RPTNO ORDER BY ORG DESC) AS ORG 
  FROM BUG.CUSTOMER_BUGS
  WHERE ORG IS NOT NULL
      
    /* handle Customer cases */
    AND CASE :customer1 
          WHEN '<All>' THEN '<All>'
          ELSE ORG END 
        LIKE :customer2
)

SELECT

  RPTHEAD.RPTNO,
  RPTHEAD.SUBJECT AS "SUBJECT",
      
  CASE WHEN SYSDATE - RPTHEAD.RPTDATE < 7
    THEN TO_CHAR (RPTHEAD.RPTDATE, 'DAY')
    ELSE TO_CHAR (RPTHEAD.RPTDATE, 'DS')
    END AS "DATE",
      	
  RPTHEAD.RPTD_BY AS "REPORTED_BY",
  RPTHEAD.PROGRAMMER AS "ASSIGNED_TO",
  RPTHEAD.UTILITY_VERSION AS "VERSION",
  BUGSTAT.STATUS || ' - ' || BUGSTAT.SDESCRIP AS "STATUS",
  BUGSTAT.STATUS AS "STATUS_CODE",
  BUGSTAT_STATE.STATE AS "STATE",
  RPTHEAD.CS_PRIORITY AS "SEVERITY",
      
  CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL
    THEN '<Unassigned>' ELSE RPTHEAD.PRI_FOR_DEV
    END AS "PRIORITY",
        
  RPTHEAD.CATEGORY AS "COMPONENT",
      
  CASE WHEN CUST_BUGS.ORG IS NULL
    THEN '<Internal>' ELSE CUST_BUGS.ORG 
    END AS "CUSTOMER",
      	
  BASE_RPTNO
      
      
FROM BUG.RPTHEAD 
JOIN BUG.BUGSTAT ON RPTHEAD.STATUS = BUGSTAT.STATUS 
JOIN BUG.BUGSTAT_STATE ON RPTHEAD.STATUS = BUGSTAT_STATE.STATUS 
LEFT OUTER JOIN CUST_BUGS ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO

WHERE RPTHEAD.CATEGORY LIKE :component 
  AND RPTHEAD.UTILITY_VERSION LIKE :version 
  AND RPTHEAD.RPTD_BY LIKE :reported_by
  AND RPTHEAD.PROGRAMMER LIKE :assigned_to
  AND RPTHEAD.CS_PRIORITY LIKE :severity
  
  /* handle Priority case */
  AND CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL 
        THEN '<Unassigned>'
        ELSE RPTHEAD.PRI_FOR_DEV END 
      LIKE :priority
    
  /* handle Status cases */    
  AND (RPTHEAD.STATUS LIKE :status1
  	OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')
    
  /* handle Customer cases */
  AND CASE :customer3 
        WHEN '<Internal>' THEN '<Internal>'
        WHEN '<All>' THEN '<All>'
        ELSE CUST_BUGS.ORG END
    IS NOT NULL
  

ORDER BY RPTHEAD.RPTNO DESC;


-- RPTHEAD time series query
prepare 5
WITH CUST_BUGS AS (
  
  /* select a maximum of one customer per bug report */
  SELECT DISTINCT 
    RPTNO, 
    FIRST_VALUE (ORG) 
      OVER (PARTITION BY RPTNO ORDER BY ORG DESC) AS ORG 
  FROM BUG.CUSTOMER_BUGS
  WHERE ORG IS NOT NULL
      
    /* handle Customer cases */
    AND CASE :customer1 
          WHEN '<All>' THEN '<All>'
          ELSE ORG END 
        LIKE :customer2
),

DATASET AS (

  SELECT

    RPTHEAD.RPTNO,
    TRUNC (RPTHEAD.RPTDATE) AS "RPTDATE",
    TRUNC (RPTHEAD.FIXED_DATE) AS "FIXED_DATE"        
      
  FROM BUG.RPTHEAD 
  JOIN BUG.BUGSTAT ON RPTHEAD.STATUS = BUGSTAT.STATUS 
  JOIN BUG.BUGSTAT_STATE ON RPTHEAD.STATUS = BUGSTAT_STATE.STATUS 
  LEFT OUTER JOIN CUST_BUGS ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO

  WHERE RPTHEAD.CATEGORY LIKE :component 
    AND RPTHEAD.UTILITY_VERSION LIKE :version 
    AND RPTHEAD.RPTD_BY LIKE :reported_by
    AND RPTHEAD.PROGRAMMER LIKE :assigned_to
    AND RPTHEAD.CS_PRIORITY LIKE :severity
  
    /* handle Priority case */
    AND CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL 
          THEN '<Unassigned>'
          ELSE RPTHEAD.PRI_FOR_DEV END 
        LIKE :priority
        
    /* handle Status cases */    
    AND (RPTHEAD.STATUS LIKE :status1
  	  OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')        
  
    /* handle Customer cases */
    AND CASE :customer3 
          WHEN '<Internal>' THEN '<Internal>'
          WHEN '<All>' THEN '<All>'
          ELSE CUST_BUGS.ORG END
      IS NOT NULL   
)

SELECT 

  RPTCALENDAR.RPTDATE,
  COUNT (RPTNO) AS "BUG_COUNT",

  SUM (COUNT (FIXED_DATE)) OVER (ORDER BY RPTCALENDAR.RPTDATE ASC
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM_FIXED_BUG_COUNT",
   
  SUM (COUNT (RPTNO) - COUNT (FIXED_DATE)) OVER (ORDER BY RPTCALENDAR.RPTDATE ASC
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "CUM_OPEN_BUG_COUNT"
      
FROM DATASET
RIGHT OUTER JOIN BUG.RPTCALENDAR
 ON DATASET.RPTDATE = RPTCALENDAR.RPTDATE
 
WHERE RPTCALENDAR.RPTDATE >= (SELECT MIN (RPTDATE) FROM DATASET) 
   AND RPTCALENDAR.RPTDATE <= (SELECT MAX (RPTDATE) FROM DATASET) 
 
GROUP BY RPTCALENDAR.RPTDATE 
ORDER BY RPTCALENDAR.RPTDATE ASC;


-- bug stats query
prepare 6
WITH CUST_BUGS AS (
  
  /* select a maximum of one customer per bug report */
  SELECT DISTINCT 
    RPTNO, 
    FIRST_VALUE (ORG) 
      OVER (PARTITION BY RPTNO ORDER BY ORG DESC) AS ORG 
  FROM BUG.CUSTOMER_BUGS
  WHERE ORG IS NOT NULL
      
    /* handle Customer cases */
    AND CASE :customer1 
          WHEN '<All>' THEN '<All>'
          ELSE ORG END 
        LIKE :customer2
),

DATASET AS (

  SELECT

	RPTHEAD.RPTDATE,
	RPTHEAD.CS_PRIORITY,
	RPTHEAD.PRI_FOR_DEV,
    RPTHEAD.FIXED_DATE,
    CUST_BUGS.ORG       
      
  FROM BUG.RPTHEAD 
  JOIN BUG.BUGSTAT ON RPTHEAD.STATUS = BUGSTAT.STATUS 
  JOIN BUG.BUGSTAT_STATE ON RPTHEAD.STATUS = BUGSTAT_STATE.STATUS 
  LEFT OUTER JOIN CUST_BUGS ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO

  WHERE RPTHEAD.CATEGORY LIKE :component 
    AND RPTHEAD.UTILITY_VERSION LIKE :version 
    AND RPTHEAD.RPTD_BY LIKE :reported_by
    AND RPTHEAD.PROGRAMMER LIKE :assigned_to
    AND RPTHEAD.CS_PRIORITY LIKE :severity
  
    /* handle Priority case */
    AND CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL 
          THEN '<Unassigned>'
          ELSE RPTHEAD.PRI_FOR_DEV END 
        LIKE :priority
        
    /* handle Status cases */    
    AND (RPTHEAD.STATUS LIKE :status1
  	  OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')        
  
    /* handle Customer cases */
    AND CASE :customer3 
          WHEN '<Internal>' THEN '<Internal>'
          WHEN '<All>' THEN '<All>'
          ELSE CUST_BUGS.ORG END
      IS NOT NULL   
)

SELECT 

  COUNT (*) AS "TOTAL_BUG_COUNT", 
  COUNT (*) - COUNT (FIXED_DATE) AS "OPEN_BUG_COUNT",
  COUNT (FIXED_DATE) AS "CLOSED_BUG_COUNT",
  COUNT (ORG) AS "EXT_CUST_BUG_COUNT",
  
  ROUND (AVG (CASE WHEN FIXED_DATE IS NULL 
    THEN SYSDATE 
    ELSE FIXED_DATE 
    END - RPTDATE)) AS "AVG_DAYS_OPEN",
  
  ROUND (AVG (CS_PRIORITY), 1) AS "AVG_FILER_SEVERITY",
  ROUND (AVG (PRI_FOR_DEV), 1) AS "AVG_DEV_PRIORITY"
      
FROM DATASET;


-- component stats
prepare 7
WITH CUST_BUGS AS (
  
  /* select a maximum of one customer per bug report */
  SELECT DISTINCT 
    RPTNO, 
    FIRST_VALUE (ORG) 
      OVER (PARTITION BY RPTNO ORDER BY ORG DESC) AS ORG 
  FROM BUG.CUSTOMER_BUGS
  WHERE ORG IS NOT NULL
      
    /* handle Customer cases */
    AND CASE :customer1 
          WHEN '<All>' THEN '<All>'
          ELSE ORG END 
        LIKE :customer2
),

DATASET AS (

  SELECT

	RPTHEAD.CATEGORY      
      
  FROM BUG.RPTHEAD 
  JOIN BUG.BUGSTAT ON RPTHEAD.STATUS = BUGSTAT.STATUS 
  JOIN BUG.BUGSTAT_STATE ON RPTHEAD.STATUS = BUGSTAT_STATE.STATUS 
  LEFT OUTER JOIN CUST_BUGS ON RPTHEAD.RPTNO = CUST_BUGS.RPTNO

  WHERE RPTHEAD.CATEGORY LIKE :component 
    AND RPTHEAD.UTILITY_VERSION LIKE :version 
    AND RPTHEAD.RPTD_BY LIKE :reported_by
    AND RPTHEAD.PROGRAMMER LIKE :assigned_to
    AND RPTHEAD.CS_PRIORITY LIKE :severity
  
    /* handle Priority case */
    AND CASE WHEN RPTHEAD.PRI_FOR_DEV IS NULL 
          THEN '<Unassigned>'
          ELSE RPTHEAD.PRI_FOR_DEV END 
        LIKE :priority
        
    /* handle Status cases */    
    AND (RPTHEAD.STATUS LIKE :status1
  	  OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')        
  
    /* handle Customer cases */
    AND CASE :customer3 
          WHEN '<Internal>' THEN '<Internal>'
          WHEN '<All>' THEN '<All>'
          ELSE CUST_BUGS.ORG END
      IS NOT NULL   
)

SELECT 

  CATEGORY AS "COMPONENT", 
  COUNT (*) AS "COMPONENT_COUNT"
    
FROM DATASET
GROUP BY CATEGORY
ORDER BY COUNT (*) DESC;




-- ROWID based join
WITH CATEGORY_DIM AS (

  SELECT 
    CATEGORY,
    SUM (RPTNO) AS CATEGORY_ID,
    COUNT (*) AS CATEGORY_COUNT
  FROM RPTHEAD
  GROUP BY CATEGORY
  
),

TIME_DIM AS (

  SELECT 
    ROWID AS TIME_ID,
    RPTDATE AS RPTDATE,
    TO_CHAR (RPTDATE, 'DD') AS DAY_OF_MONTH,
    TO_CHAR (RPTDATE, 'DY') AS DAY_OF_WEEK,
    TO_CHAR (RPTDATE, 'MON') AS MONTH ,
    TO_CHAR (RPTDATE, 'YYYY') AS YEAR
  FROM RPTCALENDAR
),
 
FACTS AS (

  SELECT 
    
    TIME_ID, 
    CATEGORY_ID,
    1 AS BUG_COUNT_OPEN,
    NULL AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT 
                    CATEGORY_ID,
                    TRUNC (RPTDATE) AS OPEN_DATE
                  FROM RPTHEAD, CATEGORY_DIM
                  WHERE RPTHEAD.CATEGORY = CATEGORY_DIM.CATEGORY) OPEN_SET
  
  WHERE OPEN_DATE = TIME_DIM.RPTDATE
  
  UNION ALL
  
  SELECT 
    
    TIME_ID, 
    CATEGORY_ID,
    NULL AS BUG_COUNT_OPEN,
    1 AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT 
                    CATEGORY_ID,
                    TRUNC (FIXED_DATE) AS FIXED_DATE
                  FROM RPTHEAD, CATEGORY_DIM
                  WHERE RPTHEAD.CATEGORY = CATEGORY_DIM.CATEGORY) CLOSED_SET
  
  WHERE FIXED_DATE = TIME_DIM.RPTDATE

)

SELECT 
  
  TIME_DIM.RPTDATE,
  CATEGORY_DIM.CATEGORY,
  SUM (BUG_COUNT_OPEN) AS OPEN_COUNT,
  SUM (BUG_COUNT_CLOSED) AS FIXED_COUNT
  
FROM FACTS

INNER JOIN TIME_DIM
  ON FACTS.TIME_ID = TIME_DIM.TIME_ID

INNER JOIN CATEGORY_DIM
  ON FACTS.CATEGORY_ID = CATEGORY_DIM.CATEGORY_ID

GROUP BY TIME_DIM.RPTDATE, CATEGORY_DIM.CATEGORY
ORDER BY 1 DESC, 2
;








-- ROWNUM based join
WITH CATEGORY_DIM AS (

SELECT 
  ROWNUM AS CATEGORY_ID, 
  CATEGORY,
  CATEGORY_COUNT
FROM (
  SELECT 
    CATEGORY,
    COUNT (*) AS CATEGORY_COUNT
  FROM RPTHEAD
  GROUP BY CATEGORY
  ORDER BY CATEGORY)
  
),

TIME_DIM AS (

SELECT 
  ROWNUM AS TIME_ID,
  RPTDATE,
  DAY_OF_MONTH,
  DAY_OF_WEEK,
  MONTH,
  YEAR
FROM (
  SELECT 
    RPTDATE AS RPTDATE,
    TO_CHAR (RPTDATE, 'DD') AS DAY_OF_MONTH,
    TO_CHAR (RPTDATE, 'DY') AS DAY_OF_WEEK,
    TO_CHAR (RPTDATE, 'MON') AS MONTH ,
    TO_CHAR (RPTDATE, 'YYYY') AS YEAR
  FROM RPTCALENDAR
  ORDER BY RPTDATE)
),
 
FACTS AS (

  SELECT
    
    TIME_ID AS TIME_ID, 
    CATEGORY_ID AS CATEGORY_ID,
    1 AS BUG_COUNT_OPEN,
    NULL AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT 
                    CATEGORY_ID,
                    TRUNC (RPTDATE) AS OPEN_DATE
                  FROM RPTHEAD, CATEGORY_DIM
                  WHERE RPTHEAD.CATEGORY = CATEGORY_DIM.CATEGORY) OPEN_SET
  
  WHERE OPEN_DATE = TIME_DIM.RPTDATE
  
  UNION ALL
  
  SELECT
    
    TIME_ID AS TIME_ID, 
    CATEGORY_ID AS CATEGORY_ID,
    NULL AS BUG_COUNT_OPEN,
    1 AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT 
                    CATEGORY_ID,
                    TRUNC (FIXED_DATE) AS FIXED_DATE
                  FROM RPTHEAD, CATEGORY_DIM
                  WHERE RPTHEAD.CATEGORY = CATEGORY_DIM.CATEGORY) CLOSED_SET
  
  WHERE FIXED_DATE = TIME_DIM.RPTDATE

)

SELECT 
  
  TIME_DIM.RPTDATE,
  CATEGORY_DIM.CATEGORY,
  SUM (BUG_COUNT_OPEN) AS OPEN_COUNT,
  SUM (BUG_COUNT_CLOSED) AS FIXED_COUNT
  
FROM FACTS

INNER JOIN TIME_DIM
  ON FACTS.TIME_ID = TIME_DIM.TIME_ID

INNER JOIN CATEGORY_DIM
  ON FACTS.CATEGORY_ID = CATEGORY_DIM.CATEGORY_ID

GROUP BY TIME_DIM.RPTDATE, CATEGORY_DIM.CATEGORY
ORDER BY 1 DESC, 2
;








-- ROWNUM based join decomposed into additional WITH AS clauses
WITH CATEGORY_DIM AS (

SELECT 
  ROWNUM AS CATEGORY_ID, 
  CATEGORY,
  CATEGORY_COUNT
FROM (
  SELECT 
    CATEGORY,
    COUNT (*) AS CATEGORY_COUNT
  FROM RPTHEAD
  GROUP BY CATEGORY
  ORDER BY CATEGORY)
),

TIME_DIM AS (

SELECT 
  ROWNUM AS TIME_ID,
  RPTDATE,
  DAY_OF_MONTH,
  DAY_OF_WEEK,
  MONTH,
  YEAR
FROM (
  SELECT 
    RPTDATE AS RPTDATE,
    TO_CHAR (RPTDATE, 'DD') AS DAY_OF_MONTH,
    TO_CHAR (RPTDATE, 'DY') AS DAY_OF_WEEK,
    TO_CHAR (RPTDATE, 'MON') AS MONTH ,
    TO_CHAR (RPTDATE, 'YYYY') AS YEAR
  FROM RPTCALENDAR
  ORDER BY RPTDATE)
),

CATEGORY_DATES AS (

  SELECT 
    CATEGORY_ID,
    TRUNC (RPTDATE) AS OPEN_DATE,
    TRUNC (FIXED_DATE) AS FIXED_DATE
  FROM RPTHEAD, CATEGORY_DIM
  WHERE RPTHEAD.CATEGORY = CATEGORY_DIM.CATEGORY
),
 
FACTS_OPEN AS (

  SELECT
    
    TIME_ID AS TIME_ID, 
    CATEGORY_ID AS CATEGORY_ID,
    1 AS BUG_COUNT_OPEN,
    NULL AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT OPEN_DATE, CATEGORY_ID FROM CATEGORY_DATES) OPEN_SET
  WHERE OPEN_DATE = TIME_DIM.RPTDATE
),

FACTS_CLOSED AS (  

  SELECT
    
    TIME_ID AS TIME_ID, 
    CATEGORY_ID AS CATEGORY_ID,
    NULL AS BUG_COUNT_OPEN,
    1 AS BUG_COUNT_CLOSED
  
  FROM TIME_DIM, (SELECT FIXED_DATE, CATEGORY_ID FROM CATEGORY_DATES) CLOSED_SET
  WHERE FIXED_DATE = TIME_DIM.RPTDATE
),

FACTS AS (

SELECT * FROM FACTS_OPEN
UNION ALL
SELECT * FROM FACTS_CLOSED

)

SELECT 
  
  TIME_DIM.RPTDATE,
  CATEGORY_DIM.CATEGORY,
  SUM (BUG_COUNT_OPEN) AS OPEN_COUNT,
  SUM (BUG_COUNT_CLOSED) AS FIXED_COUNT
  
FROM FACTS

INNER JOIN TIME_DIM
  ON FACTS.TIME_ID = TIME_DIM.TIME_ID

INNER JOIN CATEGORY_DIM
  ON FACTS.CATEGORY_ID = CATEGORY_DIM.CATEGORY_ID

GROUP BY TIME_DIM.RPTDATE, CATEGORY_DIM.CATEGORY
ORDER BY 1 DESC, 2
;


-- end index capture
autocommit 1;
Call ttIndexAdviceCaptureEnd(1);
Call ttIndexAdviceCaptureInfoGet();
Call ttIndexAdviceCaptureOutput(1);
Call ttIndexAdviceCaptureDrop(1);








