





-- A query that reports general code bug count statistics broken down by submitter
-- and product component
WITH TDBHEAD_STATS AS (

  SELECT

    CASE WHEN GROUPING (TDBD_BY) > 0
      THEN '** TOTAL **' ELSE TDBD_BY END AS "USER",

    CASE WHEN GROUPING (CATEGORY) > 0
      THEN '** TOTAL **' ELSE CATEGORY END AS "COMPONENT",

    COUNT (TDBNO) AS "BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY COUNT (TDBNO) DESC) AS "BUG COUNT RANK",

    COUNT (FIXED_DATE) AS "FIXED BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY COUNT (FIXED_DATE) DESC) AS "FIXED BUG COUNT RANK",

    COUNT (TDBNO) - COUNT (FIXED_DATE) AS "OPEN BUG COUNT",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY COUNT (TDBNO) - COUNT (FIXED_DATE) DESC) AS "OPEN BUG COUNT RANK",

    ROUND (AVG (CASE WHEN FIXED_DATE IS NULL
                THEN SYSDATE
                ELSE FIXED_DATE END - TDBDATE)) AS "AVG DAYS OPEN",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY AVG (CASE WHEN FIXED_DATE IS NULL
                    THEN SYSDATE
                    ELSE FIXED_DATE END - TDBDATE) ASC) AS "AVG DAYS OPEN RANK",

    ROUND (AVG (CS_PRIORITY), 1) AS "AVG FILER SEVERITY",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY AVG (CS_PRIORITY) ASC) AS "AVG FILER SEVERITY RANK",

    ROUND (AVG (PRI_FOR_DEV), 1) AS "AVG DEV PRIORITY",
    DENSE_RANK () OVER (PARTITION BY CATEGORY
      ORDER BY AVG (PRI_FOR_DEV) ASC) AS "AVG DEV PRIORITY RANK"

  FROM TDBHEAD

  -- exclude non product bugs
  WHERE TDBNO IN (SELECT * FROM V_CODE_BUGS)

  GROUP BY CUBE (TDBD_BY, CATEGORY)
  HAVING COUNT (TDBNO) > 100
)

SELECT * FROM TDBHEAD_STATS
ORDER BY "COMPONENT", "BUG COUNT RANK" ASC, "AVG DAYS OPEN RANK" ASC;








-- Query for R analysis of report trends
SELECT

  ALL_TDBS.MON,

  -- ALL REPORTS --
  ALL_TDBS.TDB_COUNT,
  ALL_VERSIONS.PRODUCT_VERSION,

  CASE WHEN INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT IS NULL
    THEN 0
    ELSE INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT
  END  +

    CASE WHEN EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT IS NULL
      THEN 0
      ELSE EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT
    END AS DEFECT_COUNT,


  CASE WHEN INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT IS NULL
    THEN 0
    ELSE INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT
  END +

    CASE WHEN EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT IS NULL
      THEN 0
      ELSE EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT
    END AS DEFECT_FIXED_COUNT,


  -- INTERNAL REPORTS --
  CASE WHEN INTERNAL_TDB_COUNT IS NULL
    THEN 0
    ELSE INTERNAL_TDB_COUNT
  END AS INTERNAL_TDB_COUNT,

  CASE WHEN INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT IS NULL
    THEN 0
    ELSE INTERNAL_DEFECTS.INTERNAL_DEFECT_COUNT
  END AS INTERNAL_DEFECT_COUNT,

  CASE WHEN INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT IS NULL
    THEN 0
    ELSE INTERNAL_DEFECTS_FIXED.INTERNAL_DEFECT_FIXED_COUNT
  END AS INTERNAL_DEFECT_FIXED_COUNT,



  -- EXTERNAL REPORTS --
  CASE WHEN EXTERNAL_TDB_COUNT IS NULL
    THEN 0
    ELSE EXTERNAL_TDB_COUNT
  END AS EXTERNAL_TDB_COUNT,


  CASE WHEN EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT IS NULL
    THEN 0
    ELSE EXTERNAL_DEFECTS.EXTERNAL_DEFECT_COUNT
  END AS EXTERNAL_DEFECT_COUNT,

  CASE WHEN EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT IS NULL
    THEN 0
    ELSE EXTERNAL_DEFECTS_FIXED.EXTERNAL_DEFECT_FIXED_COUNT
  END AS EXTERNAL_DEFECT_FIXED_COUNT


FROM

  (SELECT

      TRUNC(TDBDATE, 'MON') AS MON,
      COUNT (*) AS TDB_COUNT

   FROM TDBHEAD
   WHERE CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(TDBDATE, 'MON')) ALL_TDBS,

  (SELECT DISTINCT

    TRUNC(TDBDATE, 'MON') AS MON,
    FIRST_VALUE (UTILITY_VERSION)
      OVER (PARTITION BY TRUNC(TDBDATE, 'MON')
        ORDER BY COUNT (*) DESC, MAX (UTILITY_VERSION) DESC) PRODUCT_VERSION

   FROM TDBHEAD
   WHERE CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(TDBDATE, 'MON'), UTILITY_VERSION) ALL_VERSIONS,



   -- INTERNAL REPORTS --
  (SELECT

    TRUNC(TDBDATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_TDB_COUNT

   FROM TDBHEAD
   WHERE TDBNO NOT IN (SELECT TDBNO FROM CUSTOMER_BUGS)
    AND CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(TDBDATE, 'MON')) INTERNAL_TDBS,

  (SELECT

    TRUNC(TDBDATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_DEFECT_COUNT

   FROM TDBHEAD
   WHERE TDBNO NOT IN (SELECT TDBNO FROM CUSTOMER_BUGS)
     AND TDBNO IN (SELECT * FROM V_CODE_BUGS)
   GROUP BY TRUNC(TDBDATE, 'MON')) INTERNAL_DEFECTS,

  (SELECT

    TRUNC(FIXED_DATE, 'MON') AS MON,
    COUNT (*) AS INTERNAL_DEFECT_FIXED_COUNT

   FROM TDBHEAD
   WHERE TDBNO NOT IN (SELECT TDBNO FROM CUSTOMER_BUGS)
     AND TDBNO IN (SELECT * FROM V_CODE_BUGS)
     AND FIXED_DATE IS NOT NULL
   GROUP BY TRUNC(FIXED_DATE, 'MON')) INTERNAL_DEFECTS_FIXED,



  -- EXTERNAL REPORTS --
  (SELECT

    TRUNC(TDBDATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_TDB_COUNT

   FROM TDBHEAD
   WHERE TDBNO IN (SELECT TDBNO FROM CUSTOMER_BUGS)
    AND CATEGORY != 'IMPORT' AND SOURCE_SYSTEM IS NULL
   GROUP BY TRUNC(TDBDATE, 'MON')) EXTERNAL_TDBS,

  (SELECT

    TRUNC(TDBDATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_DEFECT_COUNT

   FROM TDBHEAD
   WHERE TDBNO IN (SELECT TDBNO FROM CUSTOMER_BUGS)
     AND TDBNO IN (SELECT * FROM V_CODE_BUGS)
   GROUP BY TRUNC(TDBDATE, 'MON')) EXTERNAL_DEFECTS,

  (SELECT

    TRUNC(FIXED_DATE, 'MON') AS MON,
    COUNT (*) AS EXTERNAL_DEFECT_FIXED_COUNT

   FROM TDBHEAD
   WHERE TDBNO IN (SELECT TDBNO FROM CUSTOMER_BUGS)
     AND TDBNO IN (SELECT * FROM V_CODE_BUGS)
     AND FIXED_DATE IS NOT NULL
   GROUP BY TRUNC(FIXED_DATE, 'MON')) EXTERNAL_DEFECTS_FIXED


WHERE (
  ALL_TDBS.MON = ALL_VERSIONS.MON(+) AND

  ALL_TDBS.MON = INTERNAL_TDBS.MON(+) AND
  ALL_TDBS.MON = INTERNAL_DEFECTS.MON(+) AND
  ALL_TDBS.MON = INTERNAL_DEFECTS_FIXED.MON(+) AND

  ALL_TDBS.MON = EXTERNAL_TDBS.MON(+) AND
  ALL_TDBS.MON = EXTERNAL_DEFECTS.MON(+) AND
  ALL_TDBS.MON = EXTERNAL_DEFECTS_FIXED.MON(+))

ORDER BY 1 DESC;





-- Keyword search
prepare 1
WITH SEARCH_TERMS AS
(
  SELECT
    '%' || WILDCARD AS SEARCH_STRING,
    SUBSTR (WILDCARD, 0,
      INSTR (WILDCARD, '%') - 1) AS COMMENT_SEARCH_STRING
  FROM
    (SELECT
      LTRIM (REPLACE (UPPER (:search), ' ', '%'), '%') || '%' AS WILDCARD
    FROM DUAL) UPPER_RIGHT_WILDCARD
)

SELECT DISTINCT

  TDBHEAD.TDBNO,
  UTILITY_VERSION AS "VERSION",
  TDBHEAD.CATEGORY AS "COMPONENT",
  BUGSTAT.STATUS || ' - ' || BUGSTAT.SDESCRIP AS "STATUS",
  BUGSTAT_STATE.STATE,
  SUBJECT,

  '... ' || LTRIM (
    FIRST_VALUE (COMMENTS)
      OVER (PARTITION BY TDBBODY.TDBNO
        ORDER BY INSTR (COMMENTS, COMMENT_SEARCH_STRING) DESC NULLS LAST),
    ' @.') || ' ...' AS "COMMENT"

FROM TDBHEAD, TDBBODY,
  BUGSTAT, BUGSTAT_STATE,
  SEARCH_TERMS

WHERE TDBHEAD.TDBNO = TDBBODY.TDBNO
  AND TDBHEAD.STATUS = BUGSTAT.STATUS
  AND BUGSTAT.STATUS = BUGSTAT_STATE.STATUS

AND ((UPPER (COMMENTS) LIKE SEARCH_STRING)
  OR (UPPER (SUBJECT) LIKE SEARCH_STRING))


  /* handle Status cases */
  AND (TDBHEAD.STATUS LIKE :status1
  	OR :status2 = '<' || BUGSTAT_STATE.STATE || '>')

ORDER BY 1 DESC;
